enable_cuda: True

model:
  name: 'netvlad'
  num_clusters: 16
  patch_sizes: [2,5,8]
  strides: [1,1,1]
  num_pcs: 4096
  weights: '/home/docker_place_recognition/catkin_ws/src/place_recognition/weights/mapillary_WPCA4096.pth.tar'